[tools]
julia = "1.12"

[env]
JULIA_NUM_THREADS = "auto"

[tasks]
start_pluto = "julia --project scripts/start_pluto.jl"
download_input = "julia --project scripts/download_input.jl"
copy_template = "julia --project scripts/copy_template.jl"
